#!/bin/sh
if [ -e work ]
then
	\rm -rf work
fi

vlib work
vmap work work
vlog +cover=sb -f ./vlog.args

#vsim -novopt test_alu -do "add wave -radix hex /*; run -all"
vsim -novopt test_alu  -coverage -do "coverage exclude -du test_alu; coverage save -onexit -du alu  alu.ucdb; run -all" -c
